-- Run this entire file in Supabase Dashboard > SQL Editor.
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'customer' check (role in ('customer', 'owner'))
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    price numeric(10, 2) not null check (price >= 0),
    stock integer not null default 0 check (stock >= 0),
    color text not null default 'coral',
    description text not null default '',
    image_url text
);

alter table public.products add column if not exists image_url text;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anyone can view product images" on storage.objects;
create policy "Anyone can view product images" on storage.objects for select using (bucket_id = 'product-images');

drop policy if exists "Owners can upload product images" on storage.objects;
create policy "Owners can upload product images" on storage.objects for insert with check (bucket_id = 'product-images' and exists (select 1 from public.profiles where id = auth.uid() and role = 'owner'));

create table if not exists public.carts (
    user_id uuid primary key references auth.users(id) on delete cascade,
    items jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.saved_locations (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    label text not null,
    place_name text not null,
    latitude double precision not null,
    longitude double precision not null,
    created_at timestamptz not null default now()
);

create table if not exists public.last_locations (
    user_id uuid primary key references auth.users(id) on delete cascade,
    place_name text not null,
    latitude double precision not null,
    longitude double precision not null,
    updated_at timestamptz not null default now()
);

create or replace function public.create_customer_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id) values (new.id);
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.create_customer_profile();

insert into public.products (name, price, stock, color, description)
select * from (values
    ('Desk Buddy', 12.00, 8, 'coral', 'A tiny companion for a big workday.'),
    ('Cable Creature', 16.00, 4, 'lime', 'Keeps your charging cables from escaping.'),
    ('Moon Planter', 24.00, 3, 'sky', 'A small home for a small plant.'),
    ('Mystery Print', 10.00, 12, 'gold', 'One surprise object, chosen from the studio.')
) as starter(name, price, stock, color, description)
where not exists (select 1 from public.products);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.carts enable row level security;
alter table public.saved_locations enable row level security;
alter table public.last_locations enable row level security;

drop policy if exists "Customers can read their profile" on public.profiles;
create policy "Customers can read their profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "Anyone can view products" on public.products;
create policy "Anyone can view products" on public.products for select using (true);

drop policy if exists "Owners can add products" on public.products;
create policy "Owners can add products" on public.products for insert with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'owner'));

drop policy if exists "Owners can edit products" on public.products;
create policy "Owners can edit products" on public.products for update using (exists (select 1 from public.profiles where id = auth.uid() and role = 'owner'));

drop policy if exists "Owners can delete products" on public.products;
create policy "Owners can delete products" on public.products for delete using (exists (select 1 from public.profiles where id = auth.uid() and role = 'owner'));

drop policy if exists "Users can read their cart" on public.carts;
create policy "Users can read their cart" on public.carts for select using (auth.uid() = user_id);

drop policy if exists "Users can create their cart" on public.carts;
create policy "Users can create their cart" on public.carts for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their cart" on public.carts;
create policy "Users can update their cart" on public.carts for update using (auth.uid() = user_id);

drop policy if exists "Users can read their saved locations" on public.saved_locations;
create policy "Users can read their saved locations" on public.saved_locations for select using (auth.uid() = user_id);
drop policy if exists "Users can save locations" on public.saved_locations;
create policy "Users can save locations" on public.saved_locations for insert with check (auth.uid() = user_id);
drop policy if exists "Users can delete saved locations" on public.saved_locations;
create policy "Users can delete saved locations" on public.saved_locations for delete using (auth.uid() = user_id);
drop policy if exists "Users can read their last location" on public.last_locations;
create policy "Users can read their last location" on public.last_locations for select using (auth.uid() = user_id);
drop policy if exists "Users can save their last location" on public.last_locations;
create policy "Users can save their last location" on public.last_locations for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update their last location" on public.last_locations;
create policy "Users can update their last location" on public.last_locations for update using (auth.uid() = user_id);

-- After creating your owner account, replace the email and run this once:
-- update public.profiles set role = 'owner'
-- where id = (select id from auth.users where email = 'YOUR-EMAIL@example.com');
