const commits=[
{date:'2026-09-05',category:'games',items:[['31fc714','Changed text size in games menu'],['07c454a','Changed background colors on game page'],['83f50d8','Added page breaks to games page'],['60db97f','Working on games page'],['acfbe21','Organized games into games link'],['a0d0ff2','Added games link with games in it']]},
{date:'2026-09-03',category:'shop',items:[['e79c606','Working on shop'],['3026130','Working on store'],['244cc97','Fixed water bottle catalog'],['3dacbfd','Updated new pages'],['4d8351f','Added Dice Roller, Network speed test, Random Number Generator, Random recipes, Simon Says, and a Water Bottle Catalog'],['a21b043','Updated warning screen look'],['0fee15a','Added warning to PC Bomb']]},
{date:'2026-09-03',category:'site',items:[['6efcc00','Fixed ads'],['3b72619','Fixed main screen order'],['efac44e','Added cat facts and jokes, dog facts and jokes, and fixed bugs in code'],['c3dd9e4','Fixed main screen'],['1bec4ab','Login page fixed'],['0d23d70','Added eraser to whiteboard']]},
{date:'2026-09-02',category:'games',items:[['cc1d95d','Working on 2048'],['b6fd9cc','Fixed 2048 phone usability'],['f42ad1c','Added phone functionality for 2048'],['3d9a1c6','Added new games']]},
{date:'2026-09-01',category:'site',items:[['27bb0c3','Fixed ads'],['fedcea6','Fixed new games'],['cdd8279','Fixed spelling'],['fe3c15f','Added ad banner and clock display to homepage, plus Connect 4, Hangman, Pong, and Rock Paper Scissors games']]},
{date:'2026-08-31',category:'games',items:[['b6f1672','Finally fixed Tic Tac Toe'],['a9c634d','Added Tic Tac Toe exit button'],['c501190','Added Tic Tac Toe']]},
{date:'2026-08-30',category:'shop',items:[['2546683','Fixed shop page']]},
{date:'2026-08-29',category:'shop',items:[['314b89e','Added checkout function']]}
];
const timeline=document.getElementById('timeline');const filter=document.getElementById('filter');const count=document.getElementById('commit-count');function render(){const selected=filter.value;const groups=commits.filter((group)=>selected==='all'||group.category===selected);const total=groups.reduce((sum,group)=>sum+group.items.length,0);count.textContent=`${total} highlighted commits`;timeline.innerHTML=groups.map((group)=>`<section class="day"><h2>${new Date(`${group.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</h2>${group.items.map(([hash,message])=>`<article class="commit"><div class="commit-header"><strong>${message}</strong><span class="hash">${hash}</span></div><p>git commit</p></article>`).join('')}</section>`).join('')||'<p class="commit">No milestones match that filter.</p>'}filter.addEventListener('change',render);render();
