const canvas=document.getElementById('field');const ctx=canvas.getContext('2d');const scoreText=document.getElementById('score');const timerText=document.getElementById('timer');const statusText=document.getElementById('status');const keys={};let playing=false;let time=60;let homeScore=0;let awayScore=0;let frame;let lastTime=0;const car={x:220,y:260,angle:0,speed:0,boost:100};const ball={x:450,y:260,vx:0,vy:0};
function resetPositions(){car.x=220;car.y=260;car.angle=0;car.speed=0;car.boost=100;ball.x=450;ball.y=260;ball.vx=0;ball.vy=0}
function draw(){ctx.clearRect(0,0,900,520);ctx.fillStyle='#2b9b8d';ctx.fillRect(0,0,900,520);ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=4;ctx.strokeRect(24,24,852,472);ctx.beginPath();ctx.moveTo(450,24);ctx.lineTo(450,496);ctx.stroke();ctx.beginPath();ctx.arc(450,260,75,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#d9f5e9';ctx.fillRect(0,190,24,140);ctx.fillRect(876,190,24,140);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ball.x,ball.y,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#172531';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.translate(car.x,car.y);ctx.rotate(car.angle);ctx.fillStyle='#ff9f5b';ctx.fillRect(-23,-14,46,28);ctx.fillStyle='#172531';ctx.fillRect(0,-9,15,18);ctx.fillStyle='#64d8cb';ctx.fillRect(12,-5,9,10);ctx.fillStyle='#172531';ctx.fillRect(-17,-18,11,5);ctx.fillRect(-17,13,11,5);ctx.restore();}
function scoreGoal(home){if(home)homeScore++;else awayScore++;scoreText.textContent=`${homeScore} - ${awayScore}`;statusText.textContent=home?'GOAL! You scored!':'The other team scored!';resetPositions()}
function update(delta){if(!playing)return;const forward=keys.ArrowUp||keys.w;const reverse=keys.ArrowDown||keys.s;if(forward)car.speed=Math.min(car.speed+delta*.0009,0.42);else if(reverse)car.speed=Math.max(car.speed-delta*.0008,-.2);else car.speed*=.985;if(keys.ArrowLeft||keys.a)car.angle-=delta*.003*(Math.abs(car.speed)+.4);if(keys.ArrowRight||keys.d)car.angle+=delta*.003*(Math.abs(car.speed)+.4);if(keys[' ']&&car.boost>0){car.speed+=delta*.0012;car.boost-=delta*.04}car.x+=Math.cos(car.angle)*car.speed*delta;car.y+=Math.sin(car.angle)*car.speed*delta;car.x=Math.max(45,Math.min(855,car.x));car.y=Math.max(45,Math.min(475,car.y));const dx=ball.x-car.x,dy=ball.y-car.y,dist=Math.hypot(dx,dy);if(dist<38){const force=.7;ball.vx=dx/dist*force;ball.vy=dy/dist*force}ball.x+=ball.vx*delta;ball.y+=ball.vy*delta;ball.vx*=.992;ball.vy*=.992;if(ball.y<40||ball.y>480)ball.vy*=-1;if(ball.x<0)scoreGoal(false);if(ball.x>900)scoreGoal(true);time-=delta/1000;timerText.textContent=`${Math.max(0,Math.ceil(time))}s`;if(time<=0){playing=false;statusText.textContent=`Match over: ${homeScore} - ${awayScore}`}}
function loop(now){const delta=Math.min(now-lastTime,40);lastTime=now;update(delta);draw();frame=requestAnimationFrame(loop)}
function start(){if(time<=0){resetMatch()}playing=true;statusText.textContent='Kick off! Drive into the ball.'}
function resetMatch(){cancelAnimationFrame(frame);playing=false;time=60;homeScore=0;awayScore=0;scoreText.textContent='0 - 0';timerText.textContent='60s';statusText.textContent='Score a goal to start the match.';resetPositions();draw()}
document.addEventListener('keydown',event=>{keys[event.key]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(event.key))event.preventDefault()});document.addEventListener('keyup',event=>{keys[event.key]=false});document.getElementById('start').addEventListener('click',start);document.getElementById('reset').addEventListener('click',resetMatch);resetMatch();loop(0);
